# Generated by Django 4.2.19 on 2025-03-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('salinas_mg', 'Salinas')], max_length=20, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='pix_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
