# Generated by Django 4.2.19 on 2025-03-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_user_city_user_pix_key_user_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmed_appointments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Agendamentos Confirmados para recompensa'),
        ),
    ]
