# Generated by Django 4.2.19 on 2025-03-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_confirmed_appointments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('barbeiro', 'barbeiro'), ('cliente', 'cliente')], default='barbeiro', max_length=16, verbose_name='Perfil'),
        ),
    ]
