# Generated by Django 4.2.19 on 2025-03-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
    ]
