# Generated by Django 4.2.19 on 2025-02-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='created_by',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
