# Generated by Django 4.2.19 on 2025-03-03 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='services',
            name='duration',
        ),
    ]
