# Generated by Django 4.2.19 on 2025-03-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_services_discount_remove_services_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Imagens'),
        ),
    ]
