# Generated by Django 4.2.19 on 2025-03-02 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Segunda-feira'), ('tuesday', 'Terça-feira'), ('wednesday', 'Quarta-feira'), ('thursday', 'Quinta-feira'), ('friday', 'Sexta-feira'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_dias_de_trabalho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_active', 'day_of_week'],
                'unique_together': {('barber', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='schedule.workday')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('work_day', 'time'), name='unique_time_slot_per_day'),
        ),
    ]
