# Generated by Django 4.2.19 on 2025-03-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_workday_end_time_workday_lunch_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='slot_duration',
            field=models.PositiveIntegerField(default=30, help_text='Duração de cada horário em minutos'),
        ),
    ]
