# Generated by Django 4.2.19 on 2025-03-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_workday_day_of_week'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together=set(),
        ),
    ]
