# Generated by Django 4.2.19 on 2025-03-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_workday_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workday',
            options={'ordering': ['is_active', 'weekday_order']},
        ),
        migrations.AddField(
            model_name='workday',
            name='weekday_order',
            field=models.PositiveSmallIntegerField(default=8, editable=False),
        ),
        migrations.AddIndex(
            model_name='workday',
            index=models.Index(fields=['barber', 'is_active'], name='barber_active_idx'),
        ),
    ]
