# Generated by Django 4.2.19 on 2025-03-22 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_workday_options_workday_weekday_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='unique_time_slot_per_day',
        ),
    ]
